openapi: 3.0.1
info:
  title: Fci
  version: 0.1.0
servers:
- url: "{server}:{port}/fci"
  variables:
    server:
      default: http://localhost
    port:
      default: "8080"
paths:
  /course:
    post:
      operationId: postCourse
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/COURSE'
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/COURSE'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /office:
    post:
      operationId: postOffice
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OFFICE'
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OFFICE'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /AllLecturersByOfficeID/{office_ID}:
    get:
      operationId: getAlllecturersbyofficeidOfficeId
      parameters:
      - name: office_ID
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LECTURER'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /addLecturer:
    post:
      operationId: postAddlecturer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LECTURER'
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LECTURER'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /allLecturers:
    get:
      operationId: getAlllecturers
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LECTURER'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /AllLecturersByCourseCode/{course_code}:
    get:
      operationId: getAlllecturersbycoursecodeCourseCode
      parameters:
      - name: course_code
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LECTURER'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /updateLecturerDetails:
    put:
      operationId: putUpdatelecturerdetails
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LECTURER'
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LECTURER'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /lecturer:
    delete:
      operationId: deleteLecturer
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lecturerID'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
components:
  schemas:
    lecturerID:
      required:
      - staff_number
      type: object
      properties:
        staff_number:
          type: integer
          format: int64
    ErrorPayload:
      type: object
      properties:
        reason:
          type: string
          description: Reason phrase
        path:
          type: string
          description: Request path
        method:
          type: string
          description: Method type of the request
        message:
          type: string
          description: Error message
        timestamp:
          type: string
          description: Timestamp of the error
        status:
          type: integer
          description: Relevant HTTP status code
          format: int32
    OFFICE:
      required:
      - office_ID
      - office_number
      type: object
      properties:
        office_ID:
          type: integer
          format: int64
        office_number:
          type: string
    LECTURER:
      required:
      - course_code
      - office_ID
      - staff_name
      - staff_number
      - title
      type: object
      properties:
        staff_number:
          type: integer
          format: int64
        staff_name:
          type: string
        title:
          type: string
        course_code:
          type: string
        office_ID:
          type: integer
          format: int64
    COURSE:
      type: object
      properties:
        course_code:
          type: string
        course_name:
          type: string
        NQF:
          type: integer
          format: int64
